const productos = [
    {
        id:1,
        picture:"https://cdn.oldskull.net/wp-content/uploads/2012/03/oldskull-rapozza-06.jpg",
        title:"Pintura_1",
        price: 3500,
        artist: "Dave Rapoza",
        stock: 4,
    },
    {
        id:2,
        picture:"https://colectivovisual.files.wordpress.com/2011/12/raphael_by_davidrapozaart-d47kq2i.jpg" ,
        title:"Pintura_2",
        price: 5000,
        artist: "Dave Rapoza",
        stock: 10,
    },
    {
        id:3,
        picture:"https://2.bp.blogspot.com/-wcH_ovkZGX4/Tr_d-TnjtaI/AAAAAAAABkw/t2aAVNUjXKw/s1600/Tetsuo_Akira_DaveRapoza.jpg" ,
        title:"Pintura_3",
        price: 7000,
        artist: "Dave Rapoza",
        stock: 10,
    },
    {
        id:4,
        picture:"https://carbon-media.accelerator.net/0000000eq81/7M56P9RFs4RcDnS5dLuLaN;640x970.jpeg" ,
        title:"Pintura_4",
        price: 8000,
        artist: "Dave Rapoza",
        stock: 5,
    },
    {
        id:5,
        picture:"https://www.iamag.co/wp-content/uploads/2015/10/The-Art-of-Alex-Konstad-21.jpg" ,
        title:"Pintura_5",
        price: 4000,
        artist: "Alex Konstad",
        stock: 15,
    },
    {
        id:6,
        picture:"https://pbs.twimg.com/media/FKNMFZxVQAIIXU1?format=jpg&name=large" ,
        title:"Pintura_6",
        price: 7000,
        artist: "Alex Konstad",
        stock: 19,
    },
    {
        id:7,
        picture:"https://i.redd.it/2rwxphod6ho61.jpg" ,
        title:"Pintura_7",
        price: 7000,
        artist: "Alex Konstad",
        stock: 20,
        description:"This is a gallery-quality giclée art print on 100% cotton rag archival paper, printed with archival inks. Each art print is listed by sheet size and features a minimum one-inch border.",
    },
    {
        id:8,
        picture:"https://pbs.twimg.com/media/FIHxdyEUcAIdPMi?format=jpg&name=4096x4096" ,
        title:"Pintura_8",
        price: 7000,
        artist: "Alex Konstad",
        stock: 8,
    },
    {
        id:9,
        picture:"https://cdnb.artstation.com/p/assets/images/images/034/194/607/large/kyoung-hwan-kim-hof-f.jpg?1611661600" ,
        title:"Pintura_9",
        price: 7000,
        artist: "Kyoung Hwan Kim",
        stock: 15,
    },
    {
        id:10,
        picture:"https://cdna.artstation.com/p/assets/images/images/034/194/652/large/kyoung-hwan-kim-hx-f.jpg?1611661661" ,
        title:"Pintura_10",
        price: 7000,
        artist: "Kyoung Hwan Kim",
        stock: 11,
    },
    {
        id:11,
        picture:"https://cdna.artstation.com/p/assets/images/images/034/194/656/large/kyoung-hwan-kim-mbh-f-02.jpg?1611661669" ,
        title:"Pintura_11",
        price: 7000,
        artist: "Kyoung Hwan Kim",
        stock: 15,
    },
    {
        id:12,
        picture:"https://cdnb.artstation.com/p/assets/images/images/034/194/663/large/kyoung-hwan-kim-hdd-f.jpg?1611661678" ,
        title:"Pintura_12",
        price: 7000,
        artist: "Kyoung Hwan Kim",
        stock: 10,
    },

]


module.exports ={
    productos,
}

