const productos = [
    {
        id:1,
        picture:"https://cdn.oldskull.net/wp-content/uploads/2012/03/oldskull-rapozza-06.jpg",
        title:"Pintura_1",
        price: 3500,
        artist: "daverapoza",
        stock: 4,
        category: "2D",
        description:"This is a gallery-quality giclée art print on 100% cotton rag archival paper, printed with archival inks. Each art print is listed by sheet size and features a minimum one-inch border.",
    },
    {
        id:2,
        picture:"https://colectivovisual.files.wordpress.com/2011/12/raphael_by_davidrapozaart-d47kq2i.jpg" ,
        title:"Pintura_2",
        price: 5000,
        artist: "daverapoza",
        stock: 10,
        category: "2D",
        description:"This is a gallery-quality giclée art print on 100% cotton rag archival paper, printed with archival inks. Each art print is listed by sheet size and features a minimum one-inch border.",
    },
    {
        id:3,
        picture:"https://2.bp.blogspot.com/-wcH_ovkZGX4/Tr_d-TnjtaI/AAAAAAAABkw/t2aAVNUjXKw/s1600/Tetsuo_Akira_DaveRapoza.jpg" ,
        title:"Pintura_3",
        price: 7000,
        artist: "daverapoza",
        stock: 10,
        category: "2D",
        description:"This is a gallery-quality giclée art print on 100% cotton rag archival paper, printed with archival inks. Each art print is listed by sheet size and features a minimum one-inch border.",
    },
    {
        id:4,
        picture:"https://carbon-media.accelerator.net/0000000eq81/7M56P9RFs4RcDnS5dLuLaN;640x970.jpeg" ,
        title:"Pintura_4",
        price: 8000,
        artist: "daverapoza",
        stock: 5,
        category: "2D",
        description:"This is a gallery-quality giclée art print on 100% cotton rag archival paper, printed with archival inks. Each art print is listed by sheet size and features a minimum one-inch border.",
    },
    {
        id:5,
        picture:"https://www.iamag.co/wp-content/uploads/2015/10/The-Art-of-Alex-Konstad-21.jpg" ,
        title:"Pintura_5",
        price: 4000,
        artist: "alexkonstad",
        stock: 15,
        category: "2D",
        description:"This is a gallery-quality giclée art print on 100% cotton rag archival paper, printed with archival inks. Each art print is listed by sheet size and features a minimum one-inch border.",
    },
    {
        id:6,
        picture:"https://pbs.twimg.com/media/FKNMFZxVQAIIXU1?format=jpg&name=large" ,
        title:"Pintura_6",
        price: 7000,
        artist: "alexkonstad",
        stock: 19,
        category: "2D",
        description:"This is a gallery-quality giclée art print on 100% cotton rag archival paper, printed with archival inks. Each art print is listed by sheet size and features a minimum one-inch border.",
    },
    {
        id:7,
        picture:"https://i.redd.it/2rwxphod6ho61.jpg" ,
        title:"Pintura_7",
        price: 7000,
        artist: "alexkonstad",
        stock: 20,
        category: "2D",
        description:"This is a gallery-quality giclée art print on 100% cotton rag archival paper, printed with archival inks. Each art print is listed by sheet size and features a minimum one-inch border.",
    },
    {
        id:8,
        picture:"https://pbs.twimg.com/media/FIHxdyEUcAIdPMi?format=jpg&name=4096x4096" ,
        title:"Pintura_8",
        price: 7000,
        artist: "alexkonstad",
        stock: 8,
        category: "2D",
        description:"This is a gallery-quality giclée art print on 100% cotton rag archival paper, printed with archival inks. Each art print is listed by sheet size and features a minimum one-inch border.",
    },
    {
        id:9,
        picture:"https://cdnb.artstation.com/p/assets/images/images/034/194/607/large/kyoung-hwan-kim-hof-f.jpg?1611661600" ,
        title:"Pintura_9",
        price: 7000,
        artist: "kyounghwankim",
        stock: 15,
        category: "2D",
        description:"This is a gallery-quality giclée art print on 100% cotton rag archival paper, printed with archival inks. Each art print is listed by sheet size and features a minimum one-inch border.",
    },
    {
        id:10,
        picture:"https://cdna.artstation.com/p/assets/images/images/034/194/652/large/kyoung-hwan-kim-hx-f.jpg?1611661661" ,
        title:"Pintura_10",
        price: 7000,
        artist: "kyounghwankim",
        stock: 11,
        category: "2D",
        description:"This is a gallery-quality giclée art print on 100% cotton rag archival paper, printed with archival inks. Each art print is listed by sheet size and features a minimum one-inch border.",
    },
    {
        id:11,
        picture:"https://cdna.artstation.com/p/assets/images/images/034/194/656/large/kyoung-hwan-kim-mbh-f-02.jpg?1611661669" ,
        title:"Pintura_11",
        price: 7000,
        artist: "kyounghwankim",
        stock: 15,
        category: "2D",
        description:"This is a gallery-quality giclée art print on 100% cotton rag archival paper, printed with archival inks. Each art print is listed by sheet size and features a minimum one-inch border.",
    },
    {
        id:12,
        picture:"https://cdnb.artstation.com/p/assets/images/images/034/194/663/large/kyoung-hwan-kim-hdd-f.jpg?1611661678" ,
        title:"Pintura_12",
        price: 7000,
        artist: "kyounghwankim",
        stock: 10,
        category: "2D",
        description:"This is a gallery-quality giclée art print on 100% cotton rag archival paper, printed with archival inks. Each art print is listed by sheet size and features a minimum one-inch border.",
    },
    {
        id:13,
        picture:"https://cdnb.artstation.com/p/assets/images/images/028/001/341/large/nathan-prunier-closeup-drama.jpg?1593188857" ,
        title:"Pintura_13",
        price: 2000,
        artist: "nathanprunier",
        stock: 10,
        category: "3D",
        description:"This is a gallery-quality giclée art print on 100% cotton rag archival paper, printed with archival inks. Each art print is listed by sheet size and features a minimum one-inch border.",
    },
    {
        id:14,
        picture:"https://cdnb.artstation.com/p/assets/images/images/024/805/439/large/nathan-prunier-compstartlighting-def.jpg?1583596994" ,
        title:"Pintura_14",
        price: 7000,
        artist: "nathanprunier",
        stock: 7,
        category: "3D",
        description:"This is a gallery-quality giclée art print on 100% cotton rag archival paper, printed with archival inks. Each art print is listed by sheet size and features a minimum one-inch border.",
    },
    {
        id:15,
        picture:"https://cdna.artstation.com/p/assets/images/images/015/639/792/large/nathan-prunier-rednulihgint-grotto.jpg?1549055088" ,
        title:"Pintura_15",
        price: 4000,
        artist: "nathanprunier",
        stock: 5,
        category: "3D",
        description:"This is a gallery-quality giclée art print on 100% cotton rag archival paper, printed with archival inks. Each art print is listed by sheet size and features a minimum one-inch border.",
        
    },
    {
        id:16,
        picture:"https://cdna.artstation.com/p/assets/images/images/046/367/994/large/nathan-prunier-dirt-step.jpg?1644950142" ,
        title:"Pintura_16",
        price: 3000,
        artist: "nathanprunier",
        stock: 5,
        category: "3D",
        description:"This is a gallery-quality giclée art print on 100% cotton rag archival paper, printed with archival inks. Each art print is listed by sheet size and features a minimum one-inch border.",
    },

]


module.exports ={
    productos,
}

